import type { Metadata } from "next";
import { Cormorant_Garamond, DM_Sans } from "next/font/google";
import { GeistSans } from "geist/font/sans";
import Preloader from "@/components/Preloader";
import WhatsAppButton from "@/components/WhatsAppButton";
import SoundToggle from "@/components/SoundToggle";
import "./globals.css";

const cormorant = Cormorant_Garamond({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-cormorant",
  display: "swap",
});

const dmSans = DM_Sans({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600"],
  variable: "--font-dm-sans",
  display: "swap",
});

const siteUrl = "https://www.natakainc.com";

export const metadata: Metadata = {
  metadataBase: new URL(siteUrl),

  title: {
    default: "Nataka.inc | Media & Marketing Agency in Nairobi, Kenya",
    template: "%s | Nataka.inc — Nairobi Media & Marketing",
  },

  description:
    "Nataka.inc is a top-rated media and marketing agency in Nairobi, Kenya. We offer video production, brand strategy, digital marketing, creative production, and PR for brands across East Africa. Trusted by 80+ brands.",

  // A focused set of core terms. (Google ignores the keywords meta for ranking;
  // real targeting lives in page titles, H1s, content and the service landing pages.)
  keywords: [
    "media and marketing agency Nairobi",
    "video production company Nairobi",
    "video production company Kenya",
    "creative agency Nairobi",
    "music video production Nairobi",
    "brand strategy Kenya",
    "digital marketing agency Nairobi",
    "corporate video production Kenya",
    "social media marketing Kenya",
    "PR agency Kenya",
    "influencer marketing Kenya",
    "Nataka Inc",
  ],

  authors: [{ name: "Nataka Inc", url: siteUrl }],
  creator: "Nataka Inc",
  publisher: "Nataka Inc",

  // NOTE: canonical is intentionally NOT set here. A root-level canonical is
  // inherited by every child route, which previously made every blog post and
  // /work page canonicalise to the homepage (de-indexing them). Each page now
  // declares its own canonical; the homepage's lives in app/page.tsx.

  openGraph: {
    type: "website",
    locale: "en_KE",
    url: siteUrl,
    siteName: "Nataka Inc",
    title: "Nataka.inc | Media & Marketing Agency in Nairobi, Kenya",
    description:
      "Award-winning media and marketing agency based in Nairobi, Kenya. Video production, brand strategy, digital campaigns, and PR for brands that refuse to be ignored.",
    images: [
      {
        url: `${siteUrl}/og-image.png`,
        width: 1200,
        height: 630,
        alt: "Nataka.inc — Media & Marketing Agency, Nairobi Kenya",
      },
    ],
  },

  twitter: {
    card: "summary_large_image",
    title: "Nataka.inc | Media & Marketing Agency in Nairobi, Kenya",
    description:
      "Nairobi's leading media and marketing agency. Video production, brand strategy, digital marketing & PR.",
    images: [`${siteUrl}/og-image.png`],
    creator: "@natakainc",
  },

  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },

  verification: {
    google: "e223ee2dafac8bcd",
  },

  category: "business",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en-KE" className={`${cormorant.variable} ${dmSans.variable} ${GeistSans.variable}`}>
      <head>
        {/* Preconnect to Google Fonts for performance */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />

        {/* Geo targeting signals — tells search engines this business is in Kenya */}
        <meta name="geo.region" content="KE-30" />
        <meta name="geo.placename" content="Nairobi, Kenya" />
        <meta name="geo.position" content="-1.2921;36.8219" />
        <meta name="ICBM" content="-1.2921, 36.8219" />

        {/* Icons are generated by app/icon.tsx (favicon) and app/apple-icon.tsx
            (apple-touch) via Next's file conventions — no manual <link> tags,
            no 404s. */}

        {/* Single canonical entity graph, emitted site-wide so every page's
            Service/VideoObject/BlogPosting @id references resolve to one org.
            One business node (#org) + the WebSite node. No aggregateRating
            (self-serving reviews violate Google policy), no invented types,
            no dead SearchAction. */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@graph": [
                {
                  "@type": ["Organization", "LocalBusiness"],
                  "@id": `${siteUrl}/#org`,
                  name: "Nataka Inc",
                  alternateName: ["Nataka.inc", "Nataka Media", "Nataka Marketing Kenya"],
                  description:
                    "Nataka Inc is a media and marketing agency in Nairobi, Kenya offering video production, music videos, brand strategy, digital marketing, and PR for brands and artists across East Africa.",
                  url: siteUrl,
                  logo: { "@type": "ImageObject", url: `${siteUrl}/logo.png`, width: 512, height: 512 },
                  image: `${siteUrl}/og-image.png`,
                  telephone: "+254725107294",
                  email: "andrew@natakainc.com",
                  foundingDate: "2020",
                  numberOfEmployees: { "@type": "QuantitativeValue", minValue: 5, maxValue: 30 },
                  // Schema.org has no marketing/production LocalBusiness subtype,
                  // so specificity is expressed via Wikidata additionalType.
                  additionalType: [
                    "https://www.wikidata.org/wiki/Q1330607", // advertising agency
                    "https://www.wikidata.org/wiki/Q1114515", // video production
                  ],
                  knowsAbout: [
                    "video production",
                    "music video production",
                    "brand strategy",
                    "digital marketing",
                    "public relations",
                    "influencer marketing",
                  ],
                  address: {
                    "@type": "PostalAddress",
                    streetAddress: "Westlands",
                    addressLocality: "Nairobi",
                    addressRegion: "Nairobi County",
                    postalCode: "00100",
                    addressCountry: "KE",
                  },
                  geo: { "@type": "GeoCoordinates", latitude: -1.2921, longitude: 36.8219 },
                  areaServed: [
                    { "@type": "City", name: "Nairobi" },
                    { "@type": "Country", name: "Kenya" },
                    { "@type": "Country", name: "Uganda" },
                    { "@type": "Country", name: "Tanzania" },
                    { "@type": "Country", name: "Rwanda" },
                    { "@type": "AdministrativeArea", name: "East Africa" },
                  ],
                  openingHoursSpecification: [
                    {
                      "@type": "OpeningHoursSpecification",
                      dayOfWeek: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
                      opens: "09:00",
                      closes: "18:00",
                    },
                    {
                      "@type": "OpeningHoursSpecification",
                      dayOfWeek: "Saturday",
                      opens: "09:00",
                      closes: "13:00",
                    },
                  ],
                  priceRange: "KES 50,000 - 1,500,000",
                  currenciesAccepted: "KES",
                  paymentAccepted: "Cash, Bank Transfer, M-Pesa",
                  contactPoint: {
                    "@type": "ContactPoint",
                    telephone: "+254725107294",
                    email: "andrew@natakainc.com",
                    contactType: "customer service",
                    availableLanguage: ["English", "Swahili"],
                    areaServed: "KE",
                  },
                  hasOfferCatalog: {
                    "@type": "OfferCatalog",
                    name: "Media & Marketing Services",
                    itemListElement: [
                      { "@type": "Offer", itemOffered: { "@type": "Service", name: "Music Video Production", url: `${siteUrl}/services/music-video-production-nairobi` } },
                      { "@type": "Offer", itemOffered: { "@type": "Service", name: "Video Production", url: `${siteUrl}/services/video-production-nairobi` } },
                      { "@type": "Offer", itemOffered: { "@type": "Service", name: "Brand Strategy", url: `${siteUrl}/services/brand-strategy-kenya` } },
                      { "@type": "Offer", itemOffered: { "@type": "Service", name: "Digital Marketing", url: `${siteUrl}/services/digital-marketing-nairobi` } },
                    ],
                  },
                  sameAs: [
                    "https://www.instagram.com/natakainc",
                    "https://www.tiktok.com/@natakainc",
                    "https://www.linkedin.com/company/128374044",
                    "https://www.youtube.com/@natakainc",
                  ],
                },
                {
                  "@type": "WebSite",
                  "@id": `${siteUrl}/#website`,
                  url: siteUrl,
                  name: "Nataka Inc",
                  description: "Media & Marketing Agency in Nairobi, Kenya",
                  publisher: { "@id": `${siteUrl}/#org` },
                  inLanguage: "en-KE",
                },
              ],
            }),
          }}
        />
      </head>
      <body>
        <Preloader />
        {children}
        <WhatsAppButton />
        <SoundToggle />
      </body>
    </html>
  );
}
